// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyWebApiKeyForStarShopDevMode123456',
    appId: '1:109876543210:web:d79c6d05f32b7bb5b97e9e',
    messagingSenderId: '109876543210',
    projectId: 'starshop-app',
    authDomain: 'starshop-app.firebaseapp.com',
    storageBucket: 'starshop-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForStarShopBuildValidation12345',
    appId: '1:109876543210:android:3fa85f64d9f64858b97e9e',
    messagingSenderId: '109876543210',
    projectId: 'starshop-app',
    storageBucket: 'starshop-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForStarShopBuildValidation12345',
    appId: '1:109876543210:ios:3fa85f64d9f64858b97e9e',
    messagingSenderId: '109876543210',
    projectId: 'starshop-app',
    storageBucket: 'starshop-app.appspot.com',
    iosBundleId: 'com.shopease.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForStarShopBuildValidation12345',
    appId: '1:109876543210:ios:3fa85f64d9f64858b97e9e',
    messagingSenderId: '109876543210',
    projectId: 'starshop-app',
    storageBucket: 'starshop-app.appspot.com',
    iosBundleId: 'com.shopease.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForStarShopBuildValidation12345',
    appId: '1:109876543210:web:d79c6d05f32b7bb5b97e9e',
    messagingSenderId: '109876543210',
    projectId: 'starshop-app',
    storageBucket: 'starshop-app.appspot.com',
  );
}
