import '../models/notification_item_model.dart';
import '../models/order_model.dart';
import '../models/product_model.dart';

class SampleData {
  static List<ProductModel> get sampleProducts => [
    ProductModel(
      id: 'prod_elec_01',
      name: 'Wireless Noise-Canceling Headphones',
      price: 199.99,
      originalPrice: 249.99,
      discountPercent: 20,
      description:
          'Experience studio-grade acoustics and industry-leading active noise cancellation. 40-hour battery life with ultra-plush memory foam earcups.',
      imageUrl:
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
      category: 'Electronics',
      rating: 4.8,
      stock: 25,
      reviewCount: 142,
      isFeatured: true,
      sellerId: 'seller_apex_audio',
      sellerName: 'Apex Audio Labs',
      specs: {
        'Brand': 'AcoustiPro',
        'Connectivity': 'Bluetooth 5.3 + 3.5mm Aux',
        'Battery Life': 'Up to 40 Hours',
        'Noise Cancellation': 'Active Hybrid ANC (-38dB)',
        'Warranty': '2 Years Replacement',
        'Weight': '260g',
        'Color': 'Midnight Black',
      },
      reviews: [
        ProductReview(
          id: 'rev_101',
          userName: 'Rohan Sharma',
          rating: 5.0,
          comment: 'Best ANC headphones in this price bracket. Commuting on the metro is dead silent now!',
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
        ),
        ProductReview(
          id: 'rev_102',
          userName: 'Priya Mehta',
          rating: 4.5,
          comment: 'Bass response is crisp and battery lasts over a week on normal usage.',
          createdAt: DateTime.now().subtract(const Duration(days: 12)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_elec_02',
      name: 'Ultra HD AMOLED Smart Watch Series 8',
      price: 149.50,
      originalPrice: 199.00,
      discountPercent: 25,
      description:
          'All-day health tracker with SpO2, continuous heart rate, GPS route tracking, and water resistance up to 50 meters.',
      imageUrl:
          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
      category: 'Electronics',
      rating: 4.6,
      stock: 40,
      reviewCount: 98,
      isFeatured: true,
      sellerId: 'seller_fitpulse',
      sellerName: 'FitPulse Technologies',
      specs: {
        'Brand': 'FitPulse',
        'Display': '1.9" Always-On AMOLED (1000 nits)',
        'Battery': '7 Days Typical, 14 Days Saver',
        'Water Resistance': '5 ATM (50m Swimproof)',
        'Sensors': 'SpO2, Heart Rate, ECG, Barometer',
        'Warranty': '1 Year Manufacturer',
        'Color': 'Starlight Silver',
      },
      reviews: [
        ProductReview(
          id: 'rev_201',
          userName: 'Aman Verma',
          rating: 5.0,
          comment: 'Heart rate accuracy matches medical devices. Great screen visibility in bright sunlight.',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_elec_03',
      name: 'Pro Mechanical RGB Keyboard',
      price: 89.99,
      originalPrice: 119.99,
      discountPercent: 25,
      description:
          'Hot-swappable tactile switches, pre-lubed stabilizers, sound-dampening foam, and customizable per-key RGB backlighting.',
      imageUrl:
          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
      category: 'Electronics',
      rating: 4.7,
      stock: 18,
      reviewCount: 64,
      isFeatured: false,
      sellerId: 'seller_apex_audio',
      sellerName: 'Apex Audio Labs',
      specs: {
        'Brand': 'MechKey',
        'Switch Type': 'Gateron Pro Yellow (Tactile)',
        'Layout': '75% Compact (84 Keys)',
        'Backlight': 'RGB 16.8M Colors',
        'Connectivity': 'Tri-Mode: 2.4GHz + BT + USB-C',
        'Warranty': '1 Year',
        'Color': 'Retro Grey',
      },
      reviews: [
        ProductReview(
          id: 'rev_301',
          userName: 'Vikram Joshi',
          rating: 5.0,
          comment: 'The thock sound on this keyboard is pure bliss. No pinging sound whatsoever.',
          createdAt: DateTime.now().subtract(const Duration(days: 6)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_fash_01',
      name: 'Minimalist Heavyweight Cotton Hoodie',
      price: 49.99,
      originalPrice: 69.99,
      discountPercent: 28,
      description:
          'Crafted from 100% organic combed cotton with French terry fleece lining. Tailored modern fit with reinforced seams.',
      imageUrl:
          'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      category: 'Fashion',
      rating: 4.7,
      stock: 60,
      reviewCount: 76,
      isFeatured: false,
      sellerId: 'seller_threadcraft',
      sellerName: 'ThreadCraft Outfitters',
      specs: {
        'Brand': 'ThreadCraft',
        'Material': '100% Combed Organic Cotton (420 GSM)',
        'Fit': 'Oversized Streetwear Fit',
        'Care': 'Machine Wash Cold',
        'Origin': 'Made in India',
        'Color': 'Sage Green',
      },
      reviews: [
        ProductReview(
          id: 'rev_401',
          userName: 'Ananya Roy',
          rating: 5.0,
          comment: 'Super soft inside and heavyweight feel. Keeps warm without being bulky.',
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_fash_02',
      name: 'Classic Vintage Denim Jacket',
      price: 89.00,
      originalPrice: 120.00,
      discountPercent: 26,
      description:
          'Timeless indigo denim with durable brass hardware. Pre-shrunk premium weave offering comfort and unmatched street style.',
      imageUrl:
          'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
      category: 'Fashion',
      rating: 4.5,
      stock: 30,
      reviewCount: 54,
      isFeatured: false,
      sellerId: 'seller_threadcraft',
      sellerName: 'ThreadCraft Outfitters',
      specs: {
        'Brand': 'DenimLab',
        'Fabric': '14oz Selvedge Denim',
        'Closure': 'Brass Shank Buttons',
        'Pockets': '4 Functional Pockets',
        'Color': 'Vintage Medium Wash',
      },
      reviews: [
        ProductReview(
          id: 'rev_501',
          userName: 'Suresh Menon',
          rating: 4.5,
          comment: 'Sturdy denim that looks even better with age.',
          createdAt: DateTime.now().subtract(const Duration(days: 8)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_fash_03',
      name: 'All-Terrain Breathable Running Shoes',
      price: 119.99,
      originalPrice: 159.99,
      discountPercent: 25,
      description:
          'Responsive nitrogen-infused foam midsole with high-grip rubber outsole. Engineered mesh upper for maximum cooling.',
      imageUrl:
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      category: 'Fashion',
      rating: 4.9,
      stock: 22,
      reviewCount: 112,
      isFeatured: true,
      sellerId: 'seller_fitpulse',
      sellerName: 'FitPulse Technologies',
      specs: {
        'Brand': 'Strider',
        'Sole': 'Nitrogen Cushioning + Vibram Outsole',
        'Weight': '210g per shoe',
        'Surface': 'Road & Light Trail',
        'Color': 'Crimson Red / Carbon Black',
      },
      reviews: [
        ProductReview(
          id: 'rev_601',
          userName: 'Kunal Singhania',
          rating: 5.0,
          comment: 'Ran a half-marathon in these with zero blisters. Phenomenal energy return.',
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_home_01',
      name: 'Smart WiFi LED Ambient Floor Lamp',
      price: 79.99,
      originalPrice: 99.99,
      discountPercent: 20,
      description:
          'Over 16 million colors with music synchronization, voice assistant compatibility (Alexa, Google Assistant), and timer routines.',
      imageUrl:
          'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
      category: 'Home',
      rating: 4.4,
      stock: 35,
      reviewCount: 42,
      isFeatured: false,
      sellerId: 'seller_lumina',
      sellerName: 'Lumina Living',
      specs: {
        'Brand': 'Lumina',
        'Light Output': '1200 Lumens RGBIC',
        'Control': 'App + RF Remote + Voice',
        'Height': '145 cm',
        'Power': '24W Energy Efficient',
      },
      reviews: [
        ProductReview(
          id: 'rev_701',
          userName: 'Neha Gupta',
          rating: 4.5,
          comment: 'Transforms the entire mood of my living room in the evening.',
          createdAt: DateTime.now().subtract(const Duration(days: 9)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_home_02',
      name: 'Precision Ceramic Coffee Bean Grinder',
      price: 65.00,
      originalPrice: 85.00,
      discountPercent: 24,
      description:
          'Conical ceramic burrs ensuring uniform grind size for Espresso, Pour-Over, and French Press. Compact brushed steel design.',
      imageUrl:
          'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80',
      category: 'Home',
      rating: 4.8,
      stock: 15,
      reviewCount: 88,
      isFeatured: true,
      sellerId: 'seller_lumina',
      sellerName: 'Lumina Living',
      specs: {
        'Brand': 'BrewCraft',
        'Burr Material': 'Industrial Ceramic',
        'Grind Settings': '18 Click Precision Dial',
        'Capacity': '40g Hopper',
        'Material': '304 Stainless Steel',
      },
      reviews: [
        ProductReview(
          id: 'rev_801',
          userName: 'Aditya Dave',
          rating: 5.0,
          comment: 'Consistent grind size without heating up the beans. Coffee tastes 10x better.',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_home_03',
      name: 'Aromatherapy Ultrasonic Diffuser',
      price: 34.99,
      originalPrice: 45.00,
      discountPercent: 22,
      description:
          'Whisper-quiet 500ml ultrasonic cool mist diffuser with 7 ambient light modes, auto shut-off, and timer settings.',
      imageUrl:
          'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
      category: 'Home',
      rating: 4.6,
      stock: 50,
      reviewCount: 39,
      isFeatured: false,
      sellerId: 'seller_lumina',
      sellerName: 'Lumina Living',
      specs: {
        'Capacity': '500 ml',
        'Runtime': 'Up to 10 Hours',
        'Coverage': '350 sq. ft.',
        'Noise Level': '< 20 dB',
      },
      reviews: [
        ProductReview(
          id: 'rev_901',
          userName: 'Divya Agarwal',
          rating: 5.0,
          comment: 'Very relaxing with lavender essential oil. Runs all night safely.',
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_book_01',
      name: 'Designing Data-Intensive Applications',
      price: 44.95,
      originalPrice: 55.00,
      discountPercent: 18,
      description:
          'The definitive architectural guide to data storage, streaming, consensus, scalability, and distributed systems by Martin Kleppmann.',
      imageUrl:
          'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
      category: 'Books',
      rating: 4.9,
      stock: 45,
      reviewCount: 230,
      isFeatured: true,
      sellerId: 'seller_bookworm',
      sellerName: 'BookWorm Publishers',
      specs: {
        'Author': 'Martin Kleppmann',
        'Publisher': "O'Reilly Media",
        'Pages': '616 Pages',
        'Language': 'English',
        'Format': 'Paperback / Hardcover',
      },
      reviews: [
        ProductReview(
          id: 'rev_1001',
          userName: 'Arjun Nambiar',
          rating: 5.0,
          comment: 'Must-read for every backend engineer and system architect. Masterpiece.',
          createdAt: DateTime.now().subtract(const Duration(days: 14)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_book_02',
      name: 'Atomic Habits: Proven Framework',
      price: 18.50,
      originalPrice: 27.00,
      discountPercent: 31,
      description:
          'Transform your life with small changes that lead to remarkable results. Practical strategies to break bad patterns by James Clear.',
      imageUrl:
          'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
      category: 'Books',
      rating: 4.9,
      stock: 80,
      reviewCount: 380,
      isFeatured: true,
      sellerId: 'seller_bookworm',
      sellerName: 'BookWorm Publishers',
      specs: {
        'Author': 'James Clear',
        'Publisher': 'Avery / Penguin',
        'Pages': '320 Pages',
        'Format': 'Hardcover Deluxe Edition',
      },
      reviews: [
        ProductReview(
          id: 'rev_1101',
          userName: 'Deepak Rao',
          rating: 5.0,
          comment: 'Changed my daily routine completely. Actionable and deeply inspiring.',
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
        ),
      ],
    ),
    ProductModel(
      id: 'prod_book_03',
      name: 'Clean Code: Handbook of Agile Software',
      price: 38.00,
      originalPrice: 48.00,
      discountPercent: 21,
      description:
          'A legendary handbook of software craftsmanship. Learn to write readable, maintainable, and bug-resistant code by Robert C. Martin.',
      imageUrl:
          'https://images.unsplash.com/photo-1532012164546-f432f2e3edd9?auto=format&fit=crop&w=800&q=80',
      category: 'Books',
      rating: 4.7,
      stock: 28,
      reviewCount: 160,
      isFeatured: false,
      sellerId: 'seller_bookworm',
      sellerName: 'BookWorm Publishers',
      specs: {
        'Author': 'Robert C. Martin (Uncle Bob)',
        'Publisher': 'Prentice Hall',
        'Pages': '464 Pages',
        'Format': 'Paperback',
      },
      reviews: [
        ProductReview(
          id: 'rev_1201',
          userName: 'Mohit Chawla',
          rating: 5.0,
          comment: 'Timeless principles for code cleanliness and refactoring.',
          createdAt: DateTime.now().subtract(const Duration(days: 15)),
        ),
      ],
    ),
  ];

  static List<ShippingAddress> get sampleAddresses => [
    ShippingAddress(
      id: 'addr_home',
      label: 'Home',
      fullName: 'Abhishek Sharma',
      phone: '+91 9876543210',
      street: 'Flat 402, Block B, Green Heights, Sector 62',
      city: 'Noida',
      state: 'Uttar Pradesh',
      postalCode: '201309',
      isDefault: true,
    ),
    ShippingAddress(
      id: 'addr_work',
      label: 'Office / Tech Park',
      fullName: 'Abhishek (Developer)',
      phone: '+91 9876543210',
      street: 'Tower 3, Cyber Gateway, DLF Cyber City',
      city: 'Gurugram',
      state: 'Haryana',
      postalCode: '122002',
      isDefault: false,
    ),
  ];

  static List<NotificationItemModel> get sampleNotifications => [
    NotificationItemModel(
      id: 'notif_1',
      title: '🎉 Order Confirmed: ORD-98234',
      message: 'Your order for Wireless Noise-Canceling Headphones has been confirmed.',
      type: 'order',
      createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
    ),
    NotificationItemModel(
      id: 'notif_2',
      title: '🚚 Package Shipped with BlueDart',
      message: 'Track ID SE-BD-9284102 is on the way. Expected delivery in 2 days.',
      type: 'shipping',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    NotificationItemModel(
      id: 'notif_3',
      title: '🔥 Weekend Flash Sale (Up to 50% Off)',
      message: 'Use coupon WELCOME50 on checkout to get 50% off on all trending electronics.',
      type: 'promo',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    NotificationItemModel(
      id: 'notif_4',
      title: '📄 GST Tax Invoice Ready',
      message: 'Download invoice INV-2026-08941 from your Order Details screen.',
      type: 'order',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];
}
